//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamDaze.Web.UranusCore {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthRequestInfo", Namespace="http://www.bayometric.com")]
    [System.SerializableAttribute()]
    public partial class AuthRequestInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShowGUIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimeoutField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonID {
            get {
                return this.PersonIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonIDField, value) != true)) {
                    this.PersonIDField = value;
                    this.RaisePropertyChanged("PersonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShowGUI {
            get {
                return this.ShowGUIField;
            }
            set {
                if ((this.ShowGUIField.Equals(value) != true)) {
                    this.ShowGUIField = value;
                    this.RaisePropertyChanged("ShowGUI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Timeout {
            get {
                return this.TimeoutField;
            }
            set {
                if ((this.TimeoutField.Equals(value) != true)) {
                    this.TimeoutField = value;
                    this.RaisePropertyChanged("Timeout");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BFSResponseBase", Namespace="http://www.bayometric.com")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TeamDaze.Web.UranusCore.BFSResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TeamDaze.Web.UranusCore.BFSInfoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TeamDaze.Web.UranusCore.BFSAuthResponse))]
    public partial class BFSResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TeamDaze.Web.UranusCore.BFSClientReturnErrorCode ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TeamDaze.Web.UranusCore.BFSClientReturnErrorCode ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnMessage {
            get {
                return this.ReturnMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnMessageField, value) != true)) {
                    this.ReturnMessageField = value;
                    this.RaisePropertyChanged("ReturnMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BFSResponse", Namespace="http://www.bayometric.com")]
    [System.SerializableAttribute()]
    public partial class BFSResponse : TeamDaze.Web.UranusCore.BFSResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonFoundIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonFoundID {
            get {
                return this.PersonFoundIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonFoundIDField, value) != true)) {
                    this.PersonFoundIDField = value;
                    this.RaisePropertyChanged("PersonFoundID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonID {
            get {
                return this.PersonIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonIDField, value) != true)) {
                    this.PersonIDField = value;
                    this.RaisePropertyChanged("PersonID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BFSInfoResponse", Namespace="http://www.bayometric.com")]
    [System.SerializableAttribute()]
    public partial class BFSInfoResponse : TeamDaze.Web.UranusCore.BFSResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] RegisteredPersonsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] RegisteredPersons {
            get {
                return this.RegisteredPersonsField;
            }
            set {
                if ((object.ReferenceEquals(this.RegisteredPersonsField, value) != true)) {
                    this.RegisteredPersonsField = value;
                    this.RaisePropertyChanged("RegisteredPersons");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BFSAuthResponse", Namespace="http://www.bayometric.com")]
    [System.SerializableAttribute()]
    public partial class BFSAuthResponse : TeamDaze.Web.UranusCore.BFSResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonID {
            get {
                return this.PersonIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonIDField, value) != true)) {
                    this.PersonIDField = value;
                    this.RaisePropertyChanged("PersonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionKey {
            get {
                return this.SessionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionKeyField, value) != true)) {
                    this.SessionKeyField = value;
                    this.RaisePropertyChanged("SessionKey");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BFSClientReturnErrorCode", Namespace="http://www.bayometric.com")]
    public enum BFSClientReturnErrorCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SUCCESS = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CANCELED_BY_USER = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HIT_CONFIRMED = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NO_HIT = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALREADY_ENROLLED = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CAPTURE_TIMEOUT = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BAD_IMAGE_QUALITY = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVICE_BUSY = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INCORRECT_CALL = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        END_OF_LIST = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NO_READER_CONNECTED = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_CONNECTION_FAILED = -2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_TIMEOUT = -3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_ERROR = -4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PERSON_ID_NOT_FOUND = -5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_LICENSE = -6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LICENSE_MAX_RECORDS = -7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LICENSE_MAX_CLIENTS = -8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LICENSE_EXPIRED = -9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_SESSION = -10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SESSION_EXPIRED = -11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOT_ALLOWED_OPERATION = -12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_CREDENTIALS = -13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_PARAMETERS = -14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REQUIRES_AUTHENTICATION = -15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        USER_NOT_ACTIVE = -16,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.bayometric.com", ConfigurationName="UranusCore.UranusCore")]
    public interface UranusCore {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bayometric.com/UranusCore/CreateSession", ReplyAction="http://www.bayometric.com/UranusCore/CreateSessionResponse")]
        TeamDaze.Web.UranusCore.BFSAuthResponse CreateSession(TeamDaze.Web.UranusCore.AuthRequestInfo authRequestInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bayometric.com/UranusCore/CreateSession", ReplyAction="http://www.bayometric.com/UranusCore/CreateSessionResponse")]
        System.Threading.Tasks.Task<TeamDaze.Web.UranusCore.BFSAuthResponse> CreateSessionAsync(TeamDaze.Web.UranusCore.AuthRequestInfo authRequestInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bayometric.com/UranusCore/EndSession", ReplyAction="http://www.bayometric.com/UranusCore/EndSessionResponse")]
        TeamDaze.Web.UranusCore.BFSResponseBase EndSession(string sessionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bayometric.com/UranusCore/EndSession", ReplyAction="http://www.bayometric.com/UranusCore/EndSessionResponse")]
        System.Threading.Tasks.Task<TeamDaze.Web.UranusCore.BFSResponseBase> EndSessionAsync(string sessionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bayometric.com/UranusCore/RegisterPerson", ReplyAction="http://www.bayometric.com/UranusCore/RegisterPersonResponse")]
        TeamDaze.Web.UranusCore.BFSResponse RegisterPerson(string sessionKey, string personID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bayometric.com/UranusCore/RegisterPerson", ReplyAction="http://www.bayometric.com/UranusCore/RegisterPersonResponse")]
        System.Threading.Tasks.Task<TeamDaze.Web.UranusCore.BFSResponse> RegisterPersonAsync(string sessionKey, string personID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bayometric.com/UranusCore/UnregisterPerson", ReplyAction="http://www.bayometric.com/UranusCore/UnregisterPersonResponse")]
        TeamDaze.Web.UranusCore.BFSResponse UnregisterPerson(string sessionKey, string personID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bayometric.com/UranusCore/UnregisterPerson", ReplyAction="http://www.bayometric.com/UranusCore/UnregisterPersonResponse")]
        System.Threading.Tasks.Task<TeamDaze.Web.UranusCore.BFSResponse> UnregisterPersonAsync(string sessionKey, string personID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bayometric.com/UranusCore/Search", ReplyAction="http://www.bayometric.com/UranusCore/SearchResponse")]
        TeamDaze.Web.UranusCore.BFSResponse Search();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bayometric.com/UranusCore/Search", ReplyAction="http://www.bayometric.com/UranusCore/SearchResponse")]
        System.Threading.Tasks.Task<TeamDaze.Web.UranusCore.BFSResponse> SearchAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bayometric.com/UranusCore/SearchEx", ReplyAction="http://www.bayometric.com/UranusCore/SearchExResponse")]
        TeamDaze.Web.UranusCore.BFSResponse SearchEx(string appToken, string personID, bool showGUI, int timeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bayometric.com/UranusCore/SearchEx", ReplyAction="http://www.bayometric.com/UranusCore/SearchExResponse")]
        System.Threading.Tasks.Task<TeamDaze.Web.UranusCore.BFSResponse> SearchExAsync(string appToken, string personID, bool showGUI, int timeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bayometric.com/UranusCore/CancelSearch", ReplyAction="http://www.bayometric.com/UranusCore/CancelSearchResponse")]
        TeamDaze.Web.UranusCore.BFSResponse CancelSearch(string appToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bayometric.com/UranusCore/CancelSearch", ReplyAction="http://www.bayometric.com/UranusCore/CancelSearchResponse")]
        System.Threading.Tasks.Task<TeamDaze.Web.UranusCore.BFSResponse> CancelSearchAsync(string appToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bayometric.com/UranusCore/GetRegisteredPersons", ReplyAction="http://www.bayometric.com/UranusCore/GetRegisteredPersonsResponse")]
        TeamDaze.Web.UranusCore.BFSInfoResponse GetRegisteredPersons(int startIndex, int numberOfPersons);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bayometric.com/UranusCore/GetRegisteredPersons", ReplyAction="http://www.bayometric.com/UranusCore/GetRegisteredPersonsResponse")]
        System.Threading.Tasks.Task<TeamDaze.Web.UranusCore.BFSInfoResponse> GetRegisteredPersonsAsync(int startIndex, int numberOfPersons);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UranusCoreChannel : TeamDaze.Web.UranusCore.UranusCore, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UranusCoreClient : System.ServiceModel.ClientBase<TeamDaze.Web.UranusCore.UranusCore>, TeamDaze.Web.UranusCore.UranusCore {
        
        public UranusCoreClient() {
        }
        
        public UranusCoreClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UranusCoreClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UranusCoreClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UranusCoreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TeamDaze.Web.UranusCore.BFSAuthResponse CreateSession(TeamDaze.Web.UranusCore.AuthRequestInfo authRequestInfo) {
            return base.Channel.CreateSession(authRequestInfo);
        }
        
        public System.Threading.Tasks.Task<TeamDaze.Web.UranusCore.BFSAuthResponse> CreateSessionAsync(TeamDaze.Web.UranusCore.AuthRequestInfo authRequestInfo) {
            return base.Channel.CreateSessionAsync(authRequestInfo);
        }
        
        public TeamDaze.Web.UranusCore.BFSResponseBase EndSession(string sessionKey) {
            return base.Channel.EndSession(sessionKey);
        }
        
        public System.Threading.Tasks.Task<TeamDaze.Web.UranusCore.BFSResponseBase> EndSessionAsync(string sessionKey) {
            return base.Channel.EndSessionAsync(sessionKey);
        }
        
        public TeamDaze.Web.UranusCore.BFSResponse RegisterPerson(string sessionKey, string personID) {
            return base.Channel.RegisterPerson(sessionKey, personID);
        }
        
        public System.Threading.Tasks.Task<TeamDaze.Web.UranusCore.BFSResponse> RegisterPersonAsync(string sessionKey, string personID) {
            return base.Channel.RegisterPersonAsync(sessionKey, personID);
        }
        
        public TeamDaze.Web.UranusCore.BFSResponse UnregisterPerson(string sessionKey, string personID) {
            return base.Channel.UnregisterPerson(sessionKey, personID);
        }
        
        public System.Threading.Tasks.Task<TeamDaze.Web.UranusCore.BFSResponse> UnregisterPersonAsync(string sessionKey, string personID) {
            return base.Channel.UnregisterPersonAsync(sessionKey, personID);
        }
        
        public TeamDaze.Web.UranusCore.BFSResponse Search() {
            return base.Channel.Search();
        }
        
        public System.Threading.Tasks.Task<TeamDaze.Web.UranusCore.BFSResponse> SearchAsync() {
            return base.Channel.SearchAsync();
        }
        
        public TeamDaze.Web.UranusCore.BFSResponse SearchEx(string appToken, string personID, bool showGUI, int timeout) {
            return base.Channel.SearchEx(appToken, personID, showGUI, timeout);
        }
        
        public System.Threading.Tasks.Task<TeamDaze.Web.UranusCore.BFSResponse> SearchExAsync(string appToken, string personID, bool showGUI, int timeout) {
            return base.Channel.SearchExAsync(appToken, personID, showGUI, timeout);
        }
        
        public TeamDaze.Web.UranusCore.BFSResponse CancelSearch(string appToken) {
            return base.Channel.CancelSearch(appToken);
        }
        
        public System.Threading.Tasks.Task<TeamDaze.Web.UranusCore.BFSResponse> CancelSearchAsync(string appToken) {
            return base.Channel.CancelSearchAsync(appToken);
        }
        
        public TeamDaze.Web.UranusCore.BFSInfoResponse GetRegisteredPersons(int startIndex, int numberOfPersons) {
            return base.Channel.GetRegisteredPersons(startIndex, numberOfPersons);
        }
        
        public System.Threading.Tasks.Task<TeamDaze.Web.UranusCore.BFSInfoResponse> GetRegisteredPersonsAsync(int startIndex, int numberOfPersons) {
            return base.Channel.GetRegisteredPersonsAsync(startIndex, numberOfPersons);
        }
    }
}
